### ISSUE TITLE
Error psr-4 case sensitive

### ISSUE THREAD

**Issue by diego-sorribas** [mediatoolkit/activecampaign-v3-php#5]
Hello, I'm was struggling with an error with the namespaces, in my mac environment works fine the package but when I upload it to my server with Linux the namespaces was not working. So I renamed the folders to case-sensitive form from lists to Lists for example.

Are you agree of that?

**Comment by mattglover11** [comment]
https://www.php-fig.org/psr/psr-4/

2.3.2 The contiguous sub-namespace names after the “namespace prefix” correspond to a subdirectory within a “base directory”, in which the namespace separators represent directory separators. The subdirectory name MUST match the case of the sub-namespace names.

**Comment by mattglover11** [comment]
> Hello, I'm was struggling with an error with the namespaces, in my mac environment works fine the package but when I upload it to my server with Linux the namespaces was not working. So I renamed the folders to case-sensitive form from lists to Lists for example.
> 
> Are you agree of that?

I have submitted a PR for this fix - https://github.com/mediatoolkit/activecampaign-v3-php/pull/10
